import { Injectable, signal } from '@angular/core';

export type LanguageCode = 'en' | 'tl' | 'bi' | 'war';

type Dict = Record<string, string>;

const translations: Record<LanguageCode, Dict> = {
  en: {
    home: 'Home',
    lodgeComplaint: 'Lodge a Complaint',
    trackStatus: 'Track Status',
    announcements: 'Announcements',
    resources: 'Resources',
    login: 'Login',
    language: 'Language',
    welcomeTitle: 'WELCOME TO CAMPUSASSIST COMPLAINT SYSTEM',
    welcomeSubtitle: 'Raise concerns confidently, monitor every update, and receive clear resolutions in one platform.',
    lodgeNewComplaint: 'LODGE NEW COMPLAINT',
    systemOverview: 'SYSTEM OVERVIEW',
    howItWorks: 'HOW IT WORKS',
    recentAnnouncements: 'RECENT ANNOUNCEMENTS',
    aboutSystem: 'ABOUT THIS SYSTEM',
    supportResponse: 'SUPPORT & RESPONSE',
    officialSchoolPages: 'OFFICIAL SCHOOL PAGES',
    visitFacebook: 'Visit Facebook Page',
    aboutLead:
      'The CampusAssist Complaint System helps the university community report concerns, receive timely updates, and ensure each case is handled with accountability and transparency.',
    footerContact: 'Contact',
    footerQuickLinks: 'Quick Links',
    privacyPolicy: 'Privacy Policy',
    userGuidelines: 'User Guidelines',
    helpCenter: 'Help Center',
    officeHours: 'Office Hours',
    authSignIn: 'Secure Sign In',
    authCreate: 'Create Your Account',
    studentPortal: 'Student Portal Access',
    adminPortal: 'Administrator Portal Access',
    student: 'Student',
    admin: 'Admin',
    emailId: 'Email Address / ID',
    studentIdOrEmail: 'Student ID or Email',
    adminIdOrEmail: 'Admin ID or Email',
    password: 'Password',
    enterPassword: 'Enter your password',
    createPassword: 'Create a password',
    fullName: 'Full Name',
    enterFullName: 'Enter your full name',
    forgotPassword: 'Forgot Password?',
    createAccount: 'Create Account',
    noAccount: "Don't have an account?",
    alreadyAccount: 'Already have an account?',
    signUp: 'Sign Up',
    logIn: 'Log In',
    backHome: 'Back to Home',
    hidePassword: 'Hide password',
    showPassword: 'Show password',
    adminDemoHint: 'Admin demo account: johnroque.abina@evsu.edu.ph / Admin123',
    invalidAdminCredentials: 'Invalid admin credentials. Please try again.',
    adminDashboardOverview: 'ADMIN DASHBOARD - OVERVIEW',
    dashboard: 'Dashboard',
    newComplaints: 'New Complaints',
    inProgress: 'In-Progress',
    resolved: 'Resolved',
    userManagement: 'User Management',
    reports: 'Reports',
    settings: 'Settings',
    totalComplaintsReceived: 'Total Complaints Received',
    currentActiveComplaints: 'Current Active Complaints',
    newUnassignedComplaints: 'New Unassigned Complaints',
    resolvedComplaints: 'Resolved Complaints',
    avgResolutionTime: 'Avg. Resolution Time',
    studentSatisfaction: 'Student Satisfaction',
    monthlySubmissions: 'Monthly Complaint Submissions',
    statusBreakdown: 'Complaint Status Breakdown',
    topCategories: 'Top Complaint Categories',
    priorityComplaints: 'Priority Complaints',
    recentAssignments: 'Recent Assignments',
    notifications: 'Notifications',
    logout: 'Logout',
    sdSidebarDashboard: 'Dashboard',
    sdSidebarLodgeComplaint: 'Lodge New Complaint',
    sdSidebarMyComplaints: 'My Complaints',
    sdSidebarMyUpdates: 'My Updates',
    sdSidebarUserProfile: 'User Profile',
    sdSidebarCommunityForum: 'Community Forum',
    sdSidebarResources: 'EVSU Resources',
    sdOverviewTitle: 'Student Dashboard - Overview',
    sdMyTotalComplaints: 'My Total Complaints',
    sdUnderReview: 'Under Review',
    sdResolved: 'Resolved',
    sdSatisfiedFeedback: 'Satisfied Feedback',
    sdNewNotifications: 'New Notifications',
    sdSystemMessages: 'System Messages',
    sdMyComplaintSubmissions: 'My Complaint Submissions',
    sdTotalCountLast6Months: 'Total count, last 6 months',
    sdFeaturedForumsTopics: 'Featured Forums & Topics',
    sdTrackComplaint: 'Track Complaint',
    sdSearch: 'Search',
    sdLatestAnnouncements: 'Latest Announcements',
    sdMyComplaints: 'My Complaints',
    sdSortBy: 'Sort by',
    sdLatest: 'Latest',
    sdStatus: 'Status',
    sdRefId: 'Ref. ID',
    sdCategory: 'Category',
    sdTitle: 'Title',
    sdDateFiled: 'Date Filed',
    sdLastUpdate: 'Last Update',
    sdActions: 'Actions',
    sdViewDetailMessage: 'View Detail / Message',
    sdComplaintStatusUpdates: 'Complaint Status Updates',
    sdMyMessages: 'My Messages',
    sdSubmitNewComplaint: 'Submit New Complaint',
    sdStatusNew: 'New',
    sdStatusInReview: 'In Review',
    sdStatusActionOngoing: 'Action Ongoing',
    sdStatusResolved: 'Resolved',
    sdMonthJan: 'Jan',
    sdMonthFeb: 'Feb',
    sdMonthMar: 'Mar',
    sdMonthApr: 'Apr',
    sdMonthMay: 'May',
    sdMonthJun: 'Jun',
    sdTopicAcademicPolicy: 'Academic Policy Clarifications',
    sdTopicFacilities: 'Facilities Improvement Requests',
    sdTopicScholarship: 'Scholarship and Billing Concerns',
    sdTopicStudentServices: 'Student Services Response Guide',
    sdAge2Hours: '2 hours ago',
    sdAge3Hours: '3 hours ago',
    sdAge5Hours: '5 hours ago',
    sdAnnouncement1: 'CAS-2026-0018: Engineering Office marked your report as Action Ongoing.',
    sdAnnouncement2: 'CAS-2026-0012: Dean Office requested additional class record details.',
    sdAnnouncement3: 'CAS-2026-0004: Case marked Resolved and closed successfully.',
    sdStatusUpdate1: 'New high priority complaint from Campus A - Oct 12',
    sdStatusUpdate2: 'Reminder: 3 in-progress cases approaching deadline',
    sdMessage1: 'New high priority complaint notice from Campus A',
    sdMessage2: 'Reminder: 3 in-progress complaints approaching deadline',
    sdFooter: '© 2024 Eastern Visayas State University'
  },
  tl: {
    home: 'Tahanan',
    lodgeComplaint: 'Maghain ng Reklamo',
    trackStatus: 'Subaybayan ang Katayuan',
    announcements: 'Mga Anunsyo',
    resources: 'Mga Sanggunian',
    login: 'Mag-Login',
    language: 'Wika',
    welcomeTitle: 'MALIGAYANG PAGDATING SA CAMPUSASSIST COMPLAINT SYSTEM',
    welcomeSubtitle: 'Magpasa ng reklamo nang may kumpiyansa, subaybayan ang bawat update, at tumanggap ng malinaw na resolusyon sa iisang platform.',
    lodgeNewComplaint: 'MAGHAIN NG BAGONG REKLAMO',
    systemOverview: 'PANGKALAHATANG PAGTINGIN SA SISTEMA',
    howItWorks: 'PAANO ITO GUMAGANA',
    recentAnnouncements: 'MGA PINAKABAGONG ANUNSYO',
    aboutSystem: 'TUNGKOL SA SISTEMANG ITO',
    supportResponse: 'SUPORTA AT PAGTUGON',
    officialSchoolPages: 'OPISYAL NA MGA PAHINA NG PAARALAN',
    visitFacebook: 'Bisitahin ang Facebook Page',
    aboutLead:
      'Tinutulungan ng CampusAssist Complaint System ang komunidad ng unibersidad na mag-ulat ng mga concern, makatanggap ng napapanahong update, at matiyak na may pananagutan at malinaw ang paghawak sa bawat kaso.',
    footerContact: 'Kontak',
    footerQuickLinks: 'Mabilisang Links',
    privacyPolicy: 'Patakaran sa Privacy',
    userGuidelines: 'Gabay ng Gumagamit',
    helpCenter: 'Sentro ng Tulong',
    officeHours: 'Oras ng Opisina',
    authSignIn: 'Ligtas na Pag-sign In',
    authCreate: 'Lumikha ng Iyong Account',
    studentPortal: 'Access ng Student Portal',
    adminPortal: 'Access ng Administrator Portal',
    student: 'Estudyante',
    admin: 'Admin',
    emailId: 'Email Address / ID',
    studentIdOrEmail: 'Student ID o Email',
    adminIdOrEmail: 'Admin ID o Email',
    password: 'Password',
    enterPassword: 'Ilagay ang password',
    createPassword: 'Gumawa ng password',
    fullName: 'Buong Pangalan',
    enterFullName: 'Ilagay ang buong pangalan',
    forgotPassword: 'Nakalimutan ang Password?',
    createAccount: 'Gumawa ng Account',
    noAccount: 'Wala ka pang account?',
    alreadyAccount: 'May account ka na?',
    signUp: 'Mag-sign Up',
    logIn: 'Mag-Log In',
    backHome: 'Bumalik sa Home',
    hidePassword: 'Itago ang password',
    showPassword: 'Ipakita ang password',
    adminDemoHint: 'Admin demo account: johnroque.abina@evsu.edu.ph / Admin123',
    invalidAdminCredentials: 'Maling admin credentials. Pakisubukang muli.',
    adminDashboardOverview: 'ADMIN DASHBOARD - PANGKALAHATANG TANAW',
    dashboard: 'Dashboard',
    newComplaints: 'Bagong Reklamo',
    inProgress: 'Isinasagawa',
    resolved: 'Nalutas',
    userManagement: 'Pamamahala ng User',
    reports: 'Mga Ulat',
    settings: 'Mga Setting',
    totalComplaintsReceived: 'Kabuuang Natanggap na Reklamo',
    currentActiveComplaints: 'Kasalukuyang Aktibong Reklamo',
    newUnassignedComplaints: 'Bagong Hindi Pa Naiaatas na Reklamo',
    resolvedComplaints: 'Nalutas na Reklamo',
    avgResolutionTime: 'Karaniwang Oras ng Resolusyon',
    studentSatisfaction: 'Kasiyahan ng Estudyante',
    monthlySubmissions: 'Buwanang Naihain na Reklamo',
    statusBreakdown: 'Paghahati ng Katayuan ng Reklamo',
    topCategories: 'Nangungunang Kategorya ng Reklamo',
    priorityComplaints: 'Mga Prayoridad na Reklamo',
    recentAssignments: 'Pinakahuling Naiaatas',
    notifications: 'Mga Notipikasyon',
    logout: 'Mag-Logout',
    sdSidebarDashboard: 'Dashboard',
    sdSidebarLodgeComplaint: 'Maghain ng Bagong Reklamo',
    sdSidebarMyComplaints: 'Aking Mga Reklamo',
    sdSidebarMyUpdates: 'Aking Mga Update',
    sdSidebarUserProfile: 'Profile ng User',
    sdSidebarCommunityForum: 'Forum ng Komunidad',
    sdSidebarResources: 'Mga Resource ng EVSU',
    sdOverviewTitle: 'Student Dashboard - Pangkalahatang Tanaw',
    sdMyTotalComplaints: 'Kabuuang Reklamo Ko',
    sdUnderReview: 'Sinusuri',
    sdResolved: 'Nalutas',
    sdSatisfiedFeedback: 'Nasiyahang Feedback',
    sdNewNotifications: 'Bagong Notipikasyon',
    sdSystemMessages: 'Mga Mensahe ng Sistema',
    sdMyComplaintSubmissions: 'Aking Mga Isinumiteng Reklamo',
    sdTotalCountLast6Months: 'Kabuuang bilang, huling 6 na buwan',
    sdFeaturedForumsTopics: 'Tampok na Forums at Paksa',
    sdTrackComplaint: 'Subaybayan ang Reklamo',
    sdSearch: 'Maghanap',
    sdLatestAnnouncements: 'Pinakabagong Anunsyo',
    sdMyComplaints: 'Aking Mga Reklamo',
    sdSortBy: 'Ayusin ayon sa',
    sdLatest: 'Pinakabago',
    sdStatus: 'Katayuan',
    sdRefId: 'Ref. ID',
    sdCategory: 'Kategorya',
    sdTitle: 'Pamagat',
    sdDateFiled: 'Petsa ng Paghain',
    sdLastUpdate: 'Huling Update',
    sdActions: 'Aksyon',
    sdViewDetailMessage: 'Tingnan ang Detalye / Mensahe',
    sdComplaintStatusUpdates: 'Mga Update sa Katayuan ng Reklamo',
    sdMyMessages: 'Aking Mga Mensahe',
    sdSubmitNewComplaint: 'Maghain ng Bagong Reklamo',
    sdStatusNew: 'Bago',
    sdStatusInReview: 'Sinusuri',
    sdStatusActionOngoing: 'Isinasagawa',
    sdStatusResolved: 'Nalutas',
    sdMonthJan: 'Ene',
    sdMonthFeb: 'Peb',
    sdMonthMar: 'Mar',
    sdMonthApr: 'Abr',
    sdMonthMay: 'May',
    sdMonthJun: 'Hun',
    sdTopicAcademicPolicy: 'Paglilinaw sa Patakarang Akademiko',
    sdTopicFacilities: 'Mga Kahilingan sa Pagpapabuti ng Pasilidad',
    sdTopicScholarship: 'Mga Concern sa Scholarship at Billing',
    sdTopicStudentServices: 'Gabay sa Tugon ng Student Services',
    sdAge2Hours: '2 oras ang nakalipas',
    sdAge3Hours: '3 oras ang nakalipas',
    sdAge5Hours: '5 oras ang nakalipas',
    sdAnnouncement1: 'CAS-2026-0018: Minarkahan ng Engineering Office bilang Action Ongoing.',
    sdAnnouncement2: 'CAS-2026-0012: Humingi ang Dean Office ng dagdag na class record details.',
    sdAnnouncement3: 'CAS-2026-0004: Minarkahang Resolved at naisara na ang kaso.',
    sdStatusUpdate1: 'Bagong high priority complaint mula Campus A - Oct 12',
    sdStatusUpdate2: 'Paalala: 3 in-progress cases na malapit ang deadline',
    sdMessage1: 'Bagong abiso ng high priority complaint mula Campus A',
    sdMessage2: 'Paalala: 3 in-progress complaints na paparating ang deadline',
    sdFooter: '© 2024 Eastern Visayas State University'
  },
  bi: {
    home: 'Balay',
    lodgeComplaint: 'Mosumite og Reklamo',
    trackStatus: 'Sunda ang Status',
    announcements: 'Mga Pahibalo',
    resources: 'Mga Resource',
    login: 'Sulod',
    language: 'Pinulongan',
    welcomeTitle: 'MAAYONG PAG-ABOT SA CAMPUSASSIST COMPLAINT SYSTEM',
    welcomeSubtitle: 'Mosumite og concern nga kumpiyansa, bantayi ang tanang update, ug dawata ang klarong resolusyon sa usa ka platform.',
    lodgeNewComplaint: 'MOSUMITE OG BAG-ONG REKLAMO',
    systemOverview: 'KINATIBUK-ANG TAN-AW SA SISTEMA',
    howItWorks: 'UNSAON PAGGAMIT',
    recentAnnouncements: 'PINAKABAG-ONG PAHIBALO',
    aboutSystem: 'BAHIN NIINING SISTEMA',
    supportResponse: 'SUPORTA UG TUBAG',
    officialSchoolPages: 'OPISYAL NGA MGA PAGE SA ESKWELAHAN',
    visitFacebook: 'Ablihi ang Facebook Page',
    aboutLead:
      'Ang CampusAssist Complaint System motabang sa komunidad sa unibersidad sa pagreport og concern, pagdawat og tukmang update, ug pagsiguro nga transparent ug accountable ang pagdumala sa kaso.',
    footerContact: 'Kontak',
    footerQuickLinks: 'Paspas nga Link',
    privacyPolicy: 'Patakaran sa Privacy',
    userGuidelines: 'Giya sa User',
    helpCenter: 'Sentro sa Tabang',
    officeHours: 'Oras sa Opisina',
    authSignIn: 'Luwas nga Sign In',
    authCreate: 'Paghimo sa Imong Account',
    studentPortal: 'Akses sa Student Portal',
    adminPortal: 'Akses sa Administrator Portal',
    student: 'Estudyante',
    admin: 'Admin',
    emailId: 'Email Address / ID',
    studentIdOrEmail: 'Student ID o Email',
    adminIdOrEmail: 'Admin ID o Email',
    password: 'Password',
    enterPassword: 'Ibutang ang password',
    createPassword: 'Paghimo og password',
    fullName: 'Buong Ngalan',
    enterFullName: 'Ibutang ang tibuok ngalan',
    forgotPassword: 'Nakalimot sa Password?',
    createAccount: 'Paghimo og Account',
    noAccount: 'Wala pa kay account?',
    alreadyAccount: 'Naa na kay account?',
    signUp: 'Sign Up',
    logIn: 'Log In',
    backHome: 'Balik sa Home',
    hidePassword: 'Itago ang password',
    showPassword: 'Ipakita ang password',
    adminDemoHint: 'Admin demo account: johnroque.abina@evsu.edu.ph / Admin123',
    invalidAdminCredentials: 'Sayop nga admin credentials. Palihug sulayi utro.',
    adminDashboardOverview: 'ADMIN DASHBOARD - OVERVIEW',
    dashboard: 'Dashboard',
    newComplaints: 'Bag-ong Reklamo',
    inProgress: 'Padayon',
    resolved: 'Nasulbad',
    userManagement: 'Pagdumala sa User',
    reports: 'Mga Report',
    settings: 'Settings',
    totalComplaintsReceived: 'Kinatibuk-ang Nadawat nga Reklamo',
    currentActiveComplaints: 'Kasamtangang Aktibong Reklamo',
    newUnassignedComplaints: 'Bag-ong Wala Pa Na-assign nga Reklamo',
    resolvedComplaints: 'Nasulbad nga Reklamo',
    avgResolutionTime: 'Kasagarang Oras sa Resolusyon',
    studentSatisfaction: 'Katagbawan sa Estudyante',
    monthlySubmissions: 'Binuwan nga Reklamo',
    statusBreakdown: 'Pagkabahin sa Status sa Reklamo',
    topCategories: 'Top nga Kategorya sa Reklamo',
    priorityComplaints: 'Prayoridad nga Reklamo',
    recentAssignments: 'Bag-ong Assignment',
    notifications: 'Notipikasyon',
    logout: 'Gawas',
    sdSidebarDashboard: 'Dashboard',
    sdSidebarLodgeComplaint: 'Mosumite og Bag-ong Reklamo',
    sdSidebarMyComplaints: 'Akong mga Reklamo',
    sdSidebarMyUpdates: 'Akong mga Update',
    sdSidebarUserProfile: 'User Profile',
    sdSidebarCommunityForum: 'Community Forum',
    sdSidebarResources: 'EVSU Resources',
    sdOverviewTitle: 'Student Dashboard - Overview',
    sdMyTotalComplaints: 'Akong Total Complaints',
    sdUnderReview: 'Under Review',
    sdResolved: 'Nasulbad',
    sdSatisfiedFeedback: 'Satisfied Feedback',
    sdNewNotifications: 'Bag-ong Notipikasyon',
    sdSystemMessages: 'System Messages',
    sdMyComplaintSubmissions: 'Akong Complaint Submissions',
    sdTotalCountLast6Months: 'Total count, miaging 6 ka buwan',
    sdFeaturedForumsTopics: 'Featured Forums & Topics',
    sdTrackComplaint: 'Track Complaint',
    sdSearch: 'Search',
    sdLatestAnnouncements: 'Pinakabag-ong Pahibalo',
    sdMyComplaints: 'Akong mga Reklamo',
    sdSortBy: 'Sort by',
    sdLatest: 'Latest',
    sdStatus: 'Status',
    sdRefId: 'Ref. ID',
    sdCategory: 'Category',
    sdTitle: 'Title',
    sdDateFiled: 'Date Filed',
    sdLastUpdate: 'Last Update',
    sdActions: 'Actions',
    sdViewDetailMessage: 'Tan-awa ang Detalye / Mensahe',
    sdComplaintStatusUpdates: 'Complaint Status Updates',
    sdMyMessages: 'Akong mga Mensahe',
    sdSubmitNewComplaint: 'Submit New Complaint',
    sdStatusNew: 'New',
    sdStatusInReview: 'Under Review',
    sdStatusActionOngoing: 'Action Ongoing',
    sdStatusResolved: 'Nasulbad',
    sdMonthJan: 'Ene',
    sdMonthFeb: 'Peb',
    sdMonthMar: 'Mar',
    sdMonthApr: 'Abr',
    sdMonthMay: 'May',
    sdMonthJun: 'Hun',
    sdTopicAcademicPolicy: 'Academic Policy Clarifications',
    sdTopicFacilities: 'Facilities Improvement Requests',
    sdTopicScholarship: 'Scholarship and Billing Concerns',
    sdTopicStudentServices: 'Student Services Response Guide',
    sdAge2Hours: '2 ka oras ang milabay',
    sdAge3Hours: '3 ka oras ang milabay',
    sdAge5Hours: '5 ka oras ang milabay',
    sdAnnouncement1: 'CAS-2026-0018: Engineering Office marked your report as Action Ongoing.',
    sdAnnouncement2: 'CAS-2026-0012: Dean Office requested additional class record details.',
    sdAnnouncement3: 'CAS-2026-0004: Case marked Resolved and closed successfully.',
    sdStatusUpdate1: 'New high priority complaint from Campus A - Oct 12',
    sdStatusUpdate2: 'Reminder: 3 in-progress cases approaching deadline',
    sdMessage1: 'New high priority complaint notice from Campus A',
    sdMessage2: 'Reminder: 3 in-progress complaints approaching deadline',
    sdFooter: '© 2024 Eastern Visayas State University'
  },
  war: {
    home: 'Balay',
    lodgeComplaint: 'Magpasa hin Reklamo',
    trackStatus: 'Sundan an Status',
    announcements: 'Mga Pahibaro',
    resources: 'Mga Recurso',
    login: 'Sulod',
    language: 'Yinaknan',
    welcomeTitle: 'MALIPAYON NGA PAG-ABOT HA CAMPUSASSIST COMPLAINT SYSTEM',
    welcomeSubtitle: 'Magpasa hin concern nga may pagsarig, bantayi an ngatanan nga update, ngan karawata an klaro nga resolusyon ha usa nga platform.',
    lodgeNewComplaint: 'MAGPASA HIN BAG-O NGA REKLAMO',
    systemOverview: 'KINATIBUK-AN NGA PANMULAT',
    howItWorks: 'PAANO ITON GINAGAMIT',
    recentAnnouncements: 'PINAKABAG-O NGA PAHIBARO',
    aboutSystem: 'MAHITUNGOD HINI NGA SISTEMA',
    supportResponse: 'SUPORTA NGAN BATON',
    officialSchoolPages: 'OPISYAL NGA MGA PAGE HAN ESKWELAHAN',
    visitFacebook: 'Bisitaha an Facebook Page',
    aboutLead:
      'An CampusAssist Complaint System nabulig ha komunidad han unibersidad ha pagreport hin concern, pagkarawat hin ha panahon nga update, ngan pagsiguro nga klaro ngan may accountability an pagdumara han tagsa nga kaso.',
    footerContact: 'Kontak',
    footerQuickLinks: 'Paspas nga Link',
    privacyPolicy: 'Patakaran ha Privacy',
    userGuidelines: 'Giya han User',
    helpCenter: 'Sentro hin Bulig',
    officeHours: 'Oras han Opisina',
    authSignIn: 'Luwas nga Sign In',
    authCreate: 'Paghimo han Imo Account',
    studentPortal: 'Akses han Student Portal',
    adminPortal: 'Akses han Admin Portal',
    student: 'Estudyante',
    admin: 'Admin',
    emailId: 'Email Address / ID',
    studentIdOrEmail: 'Student ID o Email',
    adminIdOrEmail: 'Admin ID o Email',
    password: 'Password',
    enterPassword: 'Ibutang an password',
    createPassword: 'Paghimo hin password',
    fullName: 'Bug-os nga Ngaran',
    enterFullName: 'Ibutang an bug-os nga ngaran',
    forgotPassword: 'Nalipat han Password?',
    createAccount: 'Paghimo Account',
    noAccount: 'Waray ka pa account?',
    alreadyAccount: 'Mayda ka na account?',
    signUp: 'Sign Up',
    logIn: 'Log In',
    backHome: 'Balik ha Home',
    hidePassword: 'Tagoi an password',
    showPassword: 'Ipakita an password',
    adminDemoHint: 'Admin demo account: johnroque.abina@evsu.edu.ph / Admin123',
    invalidAdminCredentials: 'Sayop nga admin credentials. Alayon pagsari utro.',
    adminDashboardOverview: 'ADMIN DASHBOARD - OVERVIEW',
    dashboard: 'Dashboard',
    newComplaints: 'Bag-o nga Reklamo',
    inProgress: 'Ginbubuhat',
    resolved: 'Nasulbad',
    userManagement: 'Pagdumara han User',
    reports: 'Mga Report',
    settings: 'Settings',
    totalComplaintsReceived: 'Kinatibuk-an nga Nadawat nga Reklamo',
    currentActiveComplaints: 'Yana nga Aktibo nga Reklamo',
    newUnassignedComplaints: 'Bag-o nga Waray Pa Na-assign nga Reklamo',
    resolvedComplaints: 'Nasulbad nga Reklamo',
    avgResolutionTime: 'Kasagaran nga Oras han Resolusyon',
    studentSatisfaction: 'Katagbawan han Estudyante',
    monthlySubmissions: 'Binulan nga Pagsumite',
    statusBreakdown: 'Pagbahin han Status',
    topCategories: 'Nangunguna nga Kategorya',
    priorityComplaints: 'Prayoridad nga Reklamo',
    recentAssignments: 'Pinakabag-o nga Assignment',
    notifications: 'Notipikasyon',
    logout: 'Gawas',
    sdSidebarDashboard: 'Dashboard',
    sdSidebarLodgeComplaint: 'Magpasa hin Bag-o nga Reklamo',
    sdSidebarMyComplaints: 'Akon mga Reklamo',
    sdSidebarMyUpdates: 'Akon mga Update',
    sdSidebarUserProfile: 'User Profile',
    sdSidebarCommunityForum: 'Community Forum',
    sdSidebarResources: 'EVSU Resources',
    sdOverviewTitle: 'Student Dashboard - Overview',
    sdMyTotalComplaints: 'Akon Total Complaints',
    sdUnderReview: 'Under Review',
    sdResolved: 'Nasulbad',
    sdSatisfiedFeedback: 'Satisfied Feedback',
    sdNewNotifications: 'Bag-o nga Notipikasyon',
    sdSystemMessages: 'System Messages',
    sdMyComplaintSubmissions: 'Akon Complaint Submissions',
    sdTotalCountLast6Months: 'Total count, kataposan nga 6 ka bulan',
    sdFeaturedForumsTopics: 'Featured Forums & Topics',
    sdTrackComplaint: 'Track Complaint',
    sdSearch: 'Search',
    sdLatestAnnouncements: 'Pinakabag-o nga Pahibaro',
    sdMyComplaints: 'Akon mga Reklamo',
    sdSortBy: 'Sort by',
    sdLatest: 'Latest',
    sdStatus: 'Status',
    sdRefId: 'Ref. ID',
    sdCategory: 'Category',
    sdTitle: 'Title',
    sdDateFiled: 'Date Filed',
    sdLastUpdate: 'Last Update',
    sdActions: 'Actions',
    sdViewDetailMessage: 'Kitaa an Detalye / Mensahe',
    sdComplaintStatusUpdates: 'Complaint Status Updates',
    sdMyMessages: 'Akon mga Mensahe',
    sdSubmitNewComplaint: 'Submit New Complaint',
    sdStatusNew: 'New',
    sdStatusInReview: 'Under Review',
    sdStatusActionOngoing: 'Action Ongoing',
    sdStatusResolved: 'Nasulbad',
    sdMonthJan: 'Ene',
    sdMonthFeb: 'Peb',
    sdMonthMar: 'Mar',
    sdMonthApr: 'Abr',
    sdMonthMay: 'May',
    sdMonthJun: 'Hun',
    sdTopicAcademicPolicy: 'Academic Policy Clarifications',
    sdTopicFacilities: 'Facilities Improvement Requests',
    sdTopicScholarship: 'Scholarship and Billing Concerns',
    sdTopicStudentServices: 'Student Services Response Guide',
    sdAge2Hours: '2 oras na an nakalabay',
    sdAge3Hours: '3 oras na an nakalabay',
    sdAge5Hours: '5 oras na an nakalabay',
    sdAnnouncement1: 'CAS-2026-0018: Engineering Office marked your report as Action Ongoing.',
    sdAnnouncement2: 'CAS-2026-0012: Dean Office requested additional class record details.',
    sdAnnouncement3: 'CAS-2026-0004: Case marked Resolved and closed successfully.',
    sdStatusUpdate1: 'New high priority complaint from Campus A - Oct 12',
    sdStatusUpdate2: 'Reminder: 3 in-progress cases approaching deadline',
    sdMessage1: 'New high priority complaint notice from Campus A',
    sdMessage2: 'Reminder: 3 in-progress complaints approaching deadline',
    sdFooter: '© 2024 Eastern Visayas State University'
  }
};

@Injectable({ providedIn: 'root' })
export class LanguageService {
  readonly currentLanguage = signal<LanguageCode>(this.getInitialLanguage());

  setLanguage(lang: LanguageCode): void {
    this.currentLanguage.set(lang);
    if (typeof window !== 'undefined' && window.localStorage) {
      localStorage.setItem('campusassist_lang', lang);
    }
  }

  t(key: string): string {
    const lang = this.currentLanguage();
    return translations[lang][key] ?? translations.en[key] ?? key;
  }

  private getInitialLanguage(): LanguageCode {
    if (typeof window === 'undefined' || !window.localStorage) return 'en';
    const stored = localStorage.getItem('campusassist_lang') as LanguageCode | null;
    if (stored && ['en', 'tl', 'bi', 'war'].includes(stored)) return stored;
    return 'en';
  }
}
